name: AWS CI CD
on:
  push:
    branches: [ main ]

permissions:
  id-token: write  # OIDC ke liye zaroori hai
  contents: read

jobs:
  DeployJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Login (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1 # Apna region yahan likhein

      - name: Test AWS Connection
        run: aws sts get-caller-identity # Check karne ke liye ki login successful hai

      # Example: Agar S3 pe deploy karna hai
      # - name: Deploy to S3
      #   run: aws s3 sync ./dist s3://your-bucket-name/
